<?php
// auto-generated by sfSecurityConfigHandler
// date: 2014/07/31 10:42:00
$this->security = array (
  'new' => 
  array (
    'is_secure' => true,
    'credentials' => 'admin',
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
